default: &default
  adapter: postgresql
  encoding: utf8
  <%= ENV['DB_USER'] ? 'username: ' + ENV['DB_USER'] : '' %>
  <%= ENV['DB_PASSWORD'] ? 'password: ' + ENV['DB_PASSWORD'] : '' %>
  <%= ENV['DB_HOST'] ? 'host: ' + ENV['DB_HOST'] : '' %>

development:
  <<: *default
  database: <%= ENV['DEVELOPMENT_DATABASE_NAME'] || :coins_dev %>

test: &test
  <<: *default
  database: <%= ENV['TEST_DATABASE_NAME'] || :coins_test %>

